# file: roles/tmux_install/tasks/main.yml
---
- name: Install dependencies for Debian distros
  apt:
    name:
       - 'automake'
       - 'gcc'
       - 'git'
       - 'libevent-dev'
       - 'libncurses5-dev'
    state: installed
  when: ansible_pkg_mgr == 'apt'

- name: yum install dependencies for EL distros
  yum:
    name:
      - 'automake'
      - 'byacc'
      - 'gcc'
      - 'git'
      - 'libevent-devel'
      - 'ncurses-devel'
    state: installed
  when: ansible_pkg_mgr == 'yum' or ansible_pkg_mgr == 'dnf'

- name: Git check out tmux 2.8 source master
  git:
    repo: 'https://github.com/tmux/tmux.git'
    dest: '/usr/src/tmux'
    version: '2.8'

- name: Run autogen.sh
  command: '/bin/sh autogen.sh'
  args:
    chdir: '/usr/src/tmux'
    creates: '/usr/src/tmux/configure'

- name: Run ./configure
  command: './configure'
  args:
    chdir: '/usr/src/tmux'
    creates: 'Makefile'

- name: Make tmux
  make:
    chdir: '/usr/src/tmux'

- name: Install tmux via make install
  make:
    chdir: '/usr/src/tmux'
    target: install

- name: Add /usr/local/bin to PATH via /etc/profile.d/tmux.sh
  copy:
    src: tmux.sh
    dest: '/etc/profile.d/tmux.sh'
    mode: 0644
  when: ansible_os_family == 'RedHat'

- name: Clean up
  file:
    path: '/usr/src/tmux'
    state: absent
...
