# Molecule managed
# file: molecule/default/Dockerfile.j2

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

{% if item.env is defined %}
{% for var, value in item.env.items() %}
{% if value %}
ENV {{ var }} {{ value }}
{% endif %}
{% endfor %}
{% endif %}

# Base on the documentation:
#
#  https://ansible.readthedocs.io/projects/molecule/examples/#customizing-the-docker-image-used-by-a-scenarioplatform

ENV ANSIBLE_USER=ansible DEPLOY_GROUP=deployer
ENV SUDO_GROUP={{'sudo' if 'ubuntu' in item.image else 'wheel' }}
ENV PACKAGE_MANAGER={{'apt' if 'ubuntu' in item.image else 'yum' }}
ENV REPO_UPDATE_CMD={{'update' if 'ubuntu' in item.image else 'repolist' }}
RUN set -xe \
  && ${PACKAGE_MANAGER} ${REPO_UPDATE_CMD} \
  && ${PACKAGE_MANAGER} -y install sudo python3 ca-certificates openssl \
  && groupadd -r ${ANSIBLE_USER} \
  && groupadd -r ${DEPLOY_GROUP} \
  && useradd -m -g ${ANSIBLE_USER} ${ANSIBLE_USER} \
  && usermod -aG ${SUDO_GROUP} ${ANSIBLE_USER} \
  && usermod -aG ${DEPLOY_GROUP} ${ANSIBLE_USER} \
  && sed -i "/^%${SUDO_GROUP}/s/ALL\$/NOPASSWD:ALL/g" /etc/sudoers

USER ansible
WORKDIR /home/ansible

# vim: ft=jinja2 number nowrap
