# file: molecule/ubuntu/molecule.yml
---
scenario:
  name: ubuntu
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu20
    image: 'ubuntu:focal'
  - name: ubuntu22
    image: 'ubuntu:jammy'
...
